name: Your Job Name

on:
  pull_request:
  push:
    branches:    
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  issues: write
  pull-requests: write

jobs:
  inspect-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Use My Composite Action
        uses: Techlete/archive-scanner@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
